colourCode=read.csv("C:/Users/Lovebonito/Downloads/Copy of COLOR CODES.csv",header=FALSE,sep=",")
A=data.frame(colourCode$V1,colourCode$V2)
B=data.frame(colourCode$V3,colourCode$V4)
C=data.frame(colourCode$V5,colourCode$V6)
D=data.frame(colourCode$V7,colourCode$V8)
colnames(A)=c("code","colour")
colnames(B)=c("code","colour")
colnames(C)=c("code","colour")
colnames(D)=c("code","colour")
colourCode_1=rbind(A,B,C,D)
colourCode_1=colourCode_1[order(colourCode_1$code),]
colourCode_2=formatC(colourCode_1$code,width=3,format ="d",flag="0")
colourCode_3=cbind(colourCode_1,colourCode_2)
colourCode_4=subset(colourCode_3, select=-c(code,X))
colnames(colourCode_4)=c("colour","code")
write.csv(colourCode_4,file="colourCode.CSV")
