D=read.csv("C:/Users/Lovebonito/Downloads/Regression Data.csv",header=T)
attach(D)
fit=lm(Total.No..of.orders~index+index.2+y.1+y.2+Feb+Mar+apr+may+jun +jul+ aug+sep+oct+nov+ dec)
library(MASS)
model_1=stepAIC(fit,direction=c("both"))
summary(model_1)
newdata = data.frame(index=50,index.2=50^2,y.1=9756,y.2=13444,Feb=0,Mar=0,apr=0,may=0,jun=0,jul=0,aug=0,sep=0,oct=0,nov=0,dec=1)
predict(fit,newdata, interval="prediction") 
hist(fit$resid)
shapiro.test(fit$resid)
plot(fit$resid)
