time=ts(read.table("C:/Users/Lovebonito/Desktop/Regression Data.csv",header=F),frequency=12,start=c(2011,1))
plot.ts(time)
timecomponets=decompose(time)
plot(timecomponets)
acf(time)
pacf(time)
fit=auto.arima(time)
fit=Arima(time,order=c(0,1,0),include.drift=T)
plot(time,col="red")
lines(fitted(fit),col="blue")
plot(fit$x,col="red")
lines(fitted(fit),col="blue")
resid=fitted(fit)-fit$x
plot(resid,type="p")
abline(h=0)
acf(resid)
qqplot(resid,fitted(fit))
Box.test(resid)